spring:
  cloud:
    gateway:
      routes:
        - id: servicio-clientes
          uri: lb://servicio-clientes
          predicates:
            - Path=/api/clientes/**
          filters:
            - StripPrefix=2
        - id: servicio-vehiculos
          uri: lb://servicio-vehiculos
          predicates:
            - Path=/api/vehiculos/**
          filters:
            - StripPrefix=2
        - id: servicio-reparaciones
          uri: lb://servicio-reparaciones
          predicates:
           - Path=/api/reparaciones/**
          filters:
            - StripPrefix=2